.PHONY: run
run:
	xrun -v200x -gui -f filelist.txt -top MIPS_pipeline_tb -access +rwc -gui

.PHONY: clean
clean:
	xrun -v200x -gui -f filelist.txt -top MIPS_pipeline_tb -access +rwc -gui -clean

.PHONY: run_core
run_core:
	xrun -v200x -gui -f filelist.txt -top MIPS_pipeline -access +rwc -gui

